[package]
name = "seedcracker"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rug = "1.26.1"
snmalloc-rs = "0.3.7"

[profile.dev]
overflow-checks = false


[profile.release]
debug = true
