[package]
name = "seedcracker"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
arrayvec = "0.7.6"
lazy_static = "1.5.0"
snmalloc-rs = { version = "0.3.7", features = ["native-cpu", "lto"] }

[profile.dev]
overflow-checks = false


[profile.release]
debug = true
codegen-units = 1
lto = true


[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "seedcracker_bench"
harness = false
